import type { Metadata } from 'next';
import { Provider } from '@/layouts/provider';
import './globals.css';

// --------------------------------------------------------------------------------------

export const metadata: Metadata = {
  title: 'Next Auth',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
